### PR TITLE
Add auto-positioning functionality

### PR DESCRIPTION
**Pull request by Norman-Amy**
There are quite a few changes, so any questions or suggestions are welcome. It's been well tested so I'm pretty confident in it. I tried to make things fairly clear, but if they aren't, let me know.

Basically the rules for auto-positioning are:
- The dialog must have an `arrow-direction` attribute set with a value.
- The show function must be called every time the dialog needs to reopen or change position so that the logic for positioning will run (the transition event logic will only fire for the initial load).
- The dialog must be given `style.left` and `style.top` properties to determine where the arrow is supposed to point.

### CODE REVIEW

**Review by jshcrowthe — APPROVED** [review]
Yes, yes, yes, yes, yes. I had the CSS styling in a branch someplace but it got lost.

Thank you so much for that.

_For reference, this is the commit I made to handle the same issue: https://github.com/jshcrowthe/dialog-el/pull/19/commits/9eecb6d29d3fb6755cafb3dfa0e49e873230e13c_

**Comment by jshcrowthe** [comment]
If you could break out the default styling portion into a separate PR since that is a bugfix (and I agree 100%), we can get that merged ASAP.

I am a little hung up on some of the design decisions that you made related to the auto positioning. I'll give a review of that soon.

**Comment by Norman-Amy** [comment]
No problem. Here's the separate PR for CSS fixes: https://github.com/jshcrowthe/dialog-el/pull/21

**Comment by jshcrowthe** [comment]
@Norman-Amy thanks for the PR! You had many of the same ideas that I did. 

I have gone over your implementation and had some questions on some design decisions:

- Why the requirement of the `arrow-direction` attr? (I think we can and should support both use cases)
- Why is there required CSS? (It feels like we could find a way to eliminate this requirement which would make using the feature easier)
- Why is it beneficial to interpreting user intent? (If a user sets a dialog with a left arrow, I don't think we should be mutating the element if they pass an anchor that would have the dialog fly off the screen)

I have also put together an implementation. Take a look at #23 and let me know what you think. I would love it if we could consolidate on a single impl.

**Comment by Norman-Amy** [comment]
The `arrow-direction` attr is what tells the dialog to use an arrow in the first place. If it isn't used it's a regular dialog, which shouldn't need the auto positioning since they generally open in the middle of the page, right? Unless I'm thinking of a modal... then I'm not sure if a regular dialog needs auto positioning or not.

The required CSS (left and top) is a way to track the starting position of the dialog. Another way I've thought of doing it would be by requiring the user to pass in the triggering event as a param for the `show()` function. From there, I should be able to get the mouse coordinates and use that for the top and left starting point. If you would prefer that, I could make it happen. The width, as I think you're already well aware, is required in order for any of this to work, so we should make sure it's included in the documentation.

I don't know about the interpreting user intent concern... I've thought about having the user pass in back-up directions as part of the `arrow-direction` attr. Then if they only passed in one direction the auto-positioning wouldn't work. I would think the user would always want their dialog to fit on the screen though, but yeah, maybe that's just my interpretation. However, that is what we have done in an existing dialog implementation.

**Comment by liechtym** [comment]
I agree with Josh that there shouldn't be required CSS. There are ways this can be done without having required CSS. I personally wouldn't have a use case where I'd care about the dialog getting placed on the left or right side of the page without the arrow, so I don't care either way. I like your implementation, @jshcrowthe although my use cases would require it to be based on positioning according to the window/document, not the offset parent.

**Comment by jshcrowthe** [comment]
Closed due to #23

**Pull request closed without merging**
